# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: sunday
      timezone: Europe/Berlin
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 0
    allow:
      - dependency-type: "all"
    versioning-strategy: "increase-if-necessary"
    insecure-external-code-execution: allow
