name: Build and Publish

on:
  push:

env:
  PYTHON_VERSION: '3.8'

jobs:

  buildAndPublish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.3
      - name: Pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --hook-stage manual --all-files
      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install poetry~=1.3.2
          poetry config --local virtualenvs.create false
          poetry install --no-interaction --no-ansi
      - name: Run Tests
        run: |
          pytest .
